### ISSUE TITLE
[CPAN-PRC] The CPAN Dist does not contain a META.json file (due to using Module-Install)

### ISSUE THREAD

**Issue by shlomif** [mlawren/p5-Sys-Cmd#3]
Hi @mlawren,

I was assigned Sys::Cmd as part of the pull-request challenge ( http://cpan-prc.org/ ). Now, the email mentioned that it does not contain the recommended `META.json` file and in order to add it, I need to convert the build system away from Module-Install (which has become undermaintained and unloved (see my review of it here - http://cpanratings.perl.org/dist/Module-Install ). The questions are:

1. Would you agree for a pull-request doing that?

2. If so, what is your preferred alternative build system. The most prominent options are plain https://metacpan.org/release/ExtUtils-MakeMaker (which I dislike but can tolerate), https://metacpan.org/release/Module-Build which is much better IMO, but not all people like it, and http://dzil.org/ which provides "maximum overkill" and which many people and I find very convenient, but someone who works from the repo is required to install quite a few deps. 

So what's the verdict?

**Comment by mlawren** [comment]
> I was assigned Sys::Cmd as part of the pull-request challenge (
> http://cpan-prc.org/ ).

Thanks for taking part!

> Now, the email mentioned that it does not contain the recommended
> `META.json` file and in order to add it, I need to convert the build
> system away from Module-Install (which has become undermaintained and
> unloved...
> 
> 1. Would you agree for a pull-request doing that?

Yes. Looks like I picked the wrong horse in that particular race...

> 2. If so, what is your preferred alternative build system. The most
> prominent options are plain
> https://metacpan.org/release/ExtUtils-MakeMaker (which I dislike but
> can tolerate), https://metacpan.org/release/Module-Build which is
> much better IMO, but not all people like it, and http://dzil.org/
> which provides "maximum overkill" and which many people and I find
> very convenient, but someone who works from the repo is required to
> install quite a few deps. 

Module::Build would be fine. Module::Build::Tiny would be even better
but I've tried that once or twice and found its defaults have never
worked with my directory names or licence text or whatever...

> So what's the verdict?

I would be happy to get a Module::Build pull request against the
*devel* branch. Extra points if you decide you want to convert the dist
dependencies to Module::Build::Pluggable::CPANfile :-) Feel free to add
your name to a matching line in the Changes file describing the change.

-- 
Mark Lawrence

**Comment by shlomif** [comment]
@mlawren: hi! Thanks for the quick reply and the information! Module-Build it is and I'll be using the devel branch for this work. Stay tuned.
